include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = InstanceXPrefs
InstanceXPrefs_FILES = IXRootListController.m
InstanceXPrefs_INSTALL_PATH = /Library/PreferenceBundles
InstanceXPrefs_FRAMEWORKS = UIKit
InstanceXPrefs_PRIVATE_FRAMEWORKS = Preferences
InstanceXPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
